# Short script to remove tiles that have missing point cloud or dtm data
# This script can be run after executing checksum_qa.py and directly uses the output files
# generated by the script.
# Jakob Assmann j.assmann@bios.au.dk 16 January 2020

import os
from dklidar import settings

# Prompt user input
confirmation_string = raw_input('Are you sure you would like to remove the files for all incompleted tiles?\n[yes/no]: ')

if(confirmation_string == 'yes' or confirmation_string == 'Yes'):
    print('Deleting LAZ files with missing DTM tiles...')
    # Remove LAZ files with missing DTMs
    with open(settings.laz_folder + '../laz_files_with_missing_dtm.txt') as f:
        files = f.read().splitlines()

    for file in files:
        os.remove(file)

    print('Done.')

    print('Deleting DTM files with missing LAZ tiles...')

    # Remove DTM files with missing LAZs
    with open(settings.laz_folder + '../dtm_files_with_missing_laz.txt') as f:
        files = f.read().splitlines()

    for file in files:
        os.remove(file)

    print('Done.')
else:
    print("No or invalid input, aborting script...")
